name: PDF upload with Markdown (cronjob)

on:
  workflow_dispatch:

  schedule:
    - cron: "*/30 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies

      - uses: actions/setup-node@v3
        with:
          node-version: 16  
          # cache: 'npm'

      - name: Generate Markdowns
        run: |
          pip install -r requirements.txt

          aws s3 cp s3://cdn.afetbilgi.com/latest.json ./latest.json

          mkdir md-generated
          mkdir md-generated/tr
          mkdir md-generated/en
          mkdir md-generated/ku
          mkdir md-generated/ar
          
          python pdf-markdown/main.py tr latest.json md-generated/tr/afetbilgi.md
          python pdf-markdown/main.py en latest.json md-generated/en/afetbilgi.md
          python pdf-markdown/main.py ku latest.json md-generated/ku/afetbilgi.md
          python pdf-markdown/main.py ar latest.json md-generated/ar/afetbilgi.md

      - name: Generate PDF
        run: |
          npm i -g md-to-pdf@latest

          cd md-generated/tr
          md-to-pdf afetbilgi.md
          cp afetbilgi.md "`date +%Y-%m-%d_%H-%M-%S`.md"
          cp afetbilgi.pdf "`date +%Y-%m-%d_%H-%M-%S`.pdf"

          cd ../en
          md-to-pdf afetbilgi.md
          cp afetbilgi.md "`date +%Y-%m-%d_%H-%M-%S`.md"
          cp afetbilgi.pdf "`date +%Y-%m-%d_%H-%M-%S`.pdf"

          cd ../ku
          md-to-pdf afetbilgi.md
          cp afetbilgi.md "`date +%Y-%m-%d_%H-%M-%S`.md"
          cp afetbilgi.pdf "`date +%Y-%m-%d_%H-%M-%S`.pdf"

          cd ../ar
          md-to-pdf afetbilgi.md
          cp afetbilgi.md "`date +%Y-%m-%d_%H-%M-%S`.md"
          cp afetbilgi.pdf "`date +%Y-%m-%d_%H-%M-%S`.pdf"

      - name: Sync PDFs
        run: aws s3 sync md-generated/. s3://cdn.afetbilgi.com/md-pdf
